export const CHARACTERS = [
  {
    id: 1,
    name: "Kethryx Kinji",
    team: "4Team",
    image: "./assets/kethryx.png",
    Raça: "Tabaxi",
    gender: "Masculino",
    age: 18,
    ageType: "exact",
    occupation: "Player",
    affiliation: ["4Team", "Claret Orders"],
    status: "Vivo"
  },
  {
    id: 2,
    name: "Olmar Coggrave",
    team: "4Team",
    image: "./assets/Olmar.png",
    Raça: "Hollow One",
    gender: "Masculino",
    age: 90,
    ageType: "exact",
    occupation: "Player",
    affiliation: "4Team",
    status: "Vivo"
  },
  {
    id: 3,
    name: "Mascarado",
    team: "Penas de Morte",
    image: "./assets/mascarado.png",
    Raça: "Hollow One",
    gender: "Masculino",
    age: "?",
    ageType: "unknown",
    occupation: "Player",
    affiliation: ["Penas de Morte", "Mascarados"],
    status: "Vivo"
  },
  {
    id: 4,
    name: "Sarali Khaszal",
    team: "Penas de Morte",
    image: "./assets/Sarali.png",
    Raça: "Tiefling",
    gender: "Feminino",
    age: 24,
    ageType: "exact",
    occupation: "Player",
    affiliation: ["Penas de Morte", "Claret Orders", "Rainha Corvo"],
    status: "Vivo"
  },
  {
    id: 5,
    name: "Jojo",
    team: "Penas de Morte",
    image: "./assets/jojo.png",
    Raça: "Meio-Elfo",
    gender: "Masculino",
    age: 25,
    ageType: "exact",
    occupation: "Player",
    affiliation: "Penas de Morte" ,
    status: "Vivo"
  },
  {
    id: 6,
    name: "Lucy",
    team: "4Team",
    image: "./assets/lucy.png",
    Raça: "Elfo",
    gender: "Feminino",
    age: 124,
    ageType: "exact",
    occupation: "Player",
    affiliation: "4Team" ,
    status: "Vivo"
  },
  {
    id: 7,
    name: "Ling Rabei",
    team: "4Team",
    image: "./assets/ling.png",
    Raça: "Humano",
    gender: "Masculino",
    age: 19,
    ageType: "exact",
    occupation: "Player",
    affiliation: ["4Team"] ,
    status: "Vivo"
  },
  {
    id: 8,
    name: "Luxiel",
    team: "4Team",
    image: "./assets/luxiel.png",
    Raça: "Drow",
    gender: "Masculino",
    age: 18,
    ageType: "exact",
    occupation: "Player",
    affiliation: ["4Team", "Luxon"] ,
    status: "Morto"
  },
  {
    id: 9,
    name: "Sayuri",
    team: "4Team",
    image: "./assets/sayuri.png",
    Raça: "Humano",
    gender: "Feminino",
    age: 19,
    ageType: "exact",
    occupation: "Player",
    affiliation: "Família Jagentooth" ,
    status: "Desconhecido"
  },
  {
    id: 10,
    name: "Dobrun Wraithraiser",
    team: "Penas de Morte",
    image: "./assets/dobrun.png",
    Raça: "Loxodonte",
    gender: "Masculino",
    age: 70,
    ageType: "exact",
    occupation: "Player",
    affiliation: ["Penas de Morte", "Asharis do Vento", "Melora"] ,
    status: "Vivo"
  },
  {
    id: 11,
    name: "Thoth Henk",
    team: "Bonebreakers",
    image: null,
    Raça: "Meio-Orc",
    gender: "Masculino",
    age: 22,
    ageType: "exact",
    occupation: "Player",
    affiliation: "Bonebreakers" ,
    status: "Desconhecido"
  },
  {
    id: 12,
    name: "Thomas Molisgard",
    team: "Bonebreakers",
    image: null,
    Raça: "Humano",
    gender: "Masculino",
    age: 23,
    ageType: "exact",
    occupation: "Player",
    affiliation: "Bonebreakers" ,
    status: "Vivo"
  },
  {
    id: 13,
    name: "Medli Hawk'tuah",
    team: "Spin-off",
    image: "./assets/medli.png",
    Raça: "Aarakocra",
    gender: "Feminino",
    age: 3,
    ageType: "exact",
    occupation: "Player",
    affiliation: ["Spin-off", "Asharis do Vento"] ,
    status: "Vivo"
  },
  {
    id: 14,
    name: "Wruz Beltune",
    team: "Liceu de Alabastro",
    image: "./assets/wruz.png",
    Raça: "Drow",
    gender: "Masculino",
    age: 18,
    ageType: "exact",
    occupation: "Player",
    affiliation: ["Liceu de Alabastro"] ,
    status: "Vivo"
  },
  {
    id: 15,
    name: "Blaidd",
    team: "Claret Orders",
    image: "./assets/blaidd.png",
    Raça: "Tabaxi",
    gender: "Masculino",
    age: 33,
    ageType: "exact",
    occupation: "NPC",
    affiliation: "Claret Orders" ,
    status: "Vivo"
  },
  {
    id: 16,
    name: "Kaito",
    team: "Solitário",
    image: "./assets/Kaito.png",
    Raça: "Humano",
    gender: "Masculino",
    age: 22,
    ageType: "exact",
    occupation: "NPC",
    affiliation: "Solitário" ,
    status: "Desconhecido"
  },
  {
    id: 17,
    name: "Bryce",
    team: "Império Dwendalian",
    image: "./assets/Bryce_Feelid.png",
    Raça: "Meio-Elfo",
    gender: "Masculino",
    age: 26,
    ageType: "exact",
    occupation: "NPC",
    affiliation: "Império Dwendalian" ,
    status: "Desconhecido"
  },
  {
    id: 18,
    name: "Darrow",
    team: "Estocada Teimosa",
    image: "./assets/darrow.png",
    Raça: "Humano",
    gender: "Masculino",
    age: 32,
    ageType: "exact",
    occupation: "NPC",
    affiliation: "Estocada Teimosa" ,
    status: "Vivo"
  },
  {
    id: 19,
    name: "Ruggie",
    team: "Solitária",
    image: "./assets/ruggie.png",
    Raça: "Humano",
    gender: "Feminino",
    age: 26,
    ageType: "exact",
    occupation: "NPC",
    affiliation: "Solitário" ,
    status: "Vivo"
  },
  {
    id: 20,
    name: "Thed",
    team: "Myriad",
    image: "./assets/thed.png",
    Raça: "Halfling",
    gender: "Masculino",
    age: 35,
    ageType: "exact",
    occupation: "NPC",
    affiliation: "Myriad" ,
    status: "Vivo"
  },
  {
    id: 21,
    name: "Pumat Sol",
    team: "Assembleia Cerberus",
    image: "./assets/pumat_sol.png",
    Raça: "Firbolg",
    gender: "Masculino",
    age: "?",
    ageType: "unknown",
    occupation: "NPC",
    affiliation: ["Assembleia Cerberus", "Lojista"] ,
    status: "Vivo"
  },
  {
    id: 22,
    name: "Trent Ikithon",
    team: "Assembleia Cerberus",
    image: "./assets/trent.png",
    Raça: "Humano",
    gender: "Masculino",
    age: 78,
    ageType: "exact",
    occupation: "NPC",
    affiliation: ["Assembleia Cerberus", "Império Dwendalian"] ,
    status: "Vivo"
  },
  {
    id: 23,
    name: "Jack",
    team: "Chupada Suprema",
    image: "./assets/Jack.png",
    Raça: "Humano",
    gender: "Masculino",
    age: "26",
    ageType: "exact",
    occupation: "NPC",
    affiliation: ["Chupada Suprema", "4Team"] ,
    status: "Morto"
  },
  {
    id: 24,
    name: "Madeline",
    team: null,
    image: "./assets/Madeline.png",
    Raça: "Tiefling",
    gender: "Feminino",
    age: 18,
    ageType: "exact",
    occupation: "NPC",
    affiliation: ["Melora"] ,
    status: "Morto"
  },
  {
    id: 25,
    name: "Nikki",
    team: "Chupada Suprema",
    image: "./assets/Nikki.png",
    Raça: "Humano",
    gender: "Feminino",
    age: 25,
    ageType: "exact",
    occupation: "NPC",
    affiliation: ["Chupada Suprema", "4Team"] ,
    status: "Vivo"
  },
  {
    id: 26,
    name: "Fenina",
    team: "Chupada Suprema",
    image: "./assets/Fenina.png",
    Raça: "Gnomo",
    gender: "Feminino",
    age: 42,
    ageType: "exact",
    occupation: "NPC",
    affiliation: ["Chupada Suprema", "4Team"] ,
    status: "Morto"
  },
  {
    id: 27,
    name: "Ilstrin",
    team: "Lolth",
    image: "./assets/ilstrin.png",
    Raça: "Drow",
    gender: "Masculino",
    age: 23,
    ageType: "exact",
    occupation: "NPC",
    affiliation: "Lolth" ,
    status: "Vivo"
  },
  {
    id: 28,
    name: "Avantika",
    team: "Devora Tempestades",
    image: "./assets/avantika.png",
    Raça: "Elfo",
    gender: "Feminino",
    age: "?",
    ageType: "unknown",
    occupation: "NPC",
    affiliation: "Devora Tempestades" ,
    status: "Morto"
  },
  {
    id: 29,
    name: "Clarice",
    team: "Claret Orders",
    image: "./assets/clarice.png",
    Raça: "Humano",
    gender: "Feminino",
    age: 21,
    ageType: "exact",
    occupation: "NPC",
    affiliation: "Claret Orders" ,
    status: "Desconhecido"
  },
  {
    id: 30,
    name: "Leylas Kryn",
    team: "Dinastia Kryn",
    image: "./assets/Leylas_Kryn.png",
    Raça: "Drow",
    gender: "Feminino",
    age: 1200,
    ageType: "atLeast",
    occupation: "NPC",
    affiliation: "Dinastia Kryn" ,
    status: "Vivo"
  },
  {
    id: 31,
    name: "Gauskiira Beltune",
    team: "Dinastia Kryn",
    image: "./assets/gauskiira.png",
    Raça: "Drow",
    gender: "Masculino",
    age: 127,
    ageType: "exact",
    occupation: "NPC",
    affiliation: "Dinastia Kryn" ,
    status: "Desconhecido"
  },
  {
    id: 32,
    name: "Quana Kryn",
    team: "Penas de Morte",
    image: "./assets/quana_kryn.png",
    Raça: "Drow",
    gender: "Feminino",
    age: 25,
    ageType: "exact",
    occupation: "NPC",
    affiliation: ["Guarda", "Dinastia Kryn"] ,
    status: "Vivo"
  },
  {
    id: 33,
    name: "Essek Thelyss",
    team: "Dinastia Kryn",
    image: "./assets/essek.png",
    Raça: "Drow",
    gender: "Masculino",
    age: 127,
    ageType: "exact",
    occupation: "NPC",
    affiliation: "Dinastia Kryn" ,
    status: "Vivo"
  },
  {
    id: 34,
    name: "Jourrael",
    team: "Lolth",
    image: "./assets/jourrael.png",
    Raça: "Drow" ,
    gender: "Feminino",
    age: "?",
    ageType: "unknown",
    occupation: "NPC",
    affiliation: "Solitário" ,
    status: "Vivo"
  },
  {
    id: 35,
    name: "Laris",
    team: "4Team",
    image: "./assets/laris.png",
    Raça: "Humano",
    gender: "Feminino",
    age: 20,
    ageType: "exact",
    occupation: "NPC",
    affiliation: "4Team" ,
    status: "Vivo"
  },
  {
    id: 36,
    name: "Ludinus Da'Leth",
    team: "Assembleia Cerberus",
    image: "./assets/ludinus.png",
    Raça: "Elfo",
    gender: "Masculino",
    age: "?",
    ageType: "unknown",
    occupation: "NPC",
    affiliation: ["Assembleia Cerberus", "Império Dwendalian"] ,
    status: "Vivo"
  },
  {
    id: 37,
    name: "Vess DeRogna",
    team: "Assembleia Cerberus",
    image: "./assets/vess_Derogna.png",
    Raça: "Elfo",
    gender: "Feminino",
    age: "?",
    ageType: "unknown",
    occupation: "NPC",
    affiliation: ["Assembleia Cerberus", "Império Dwendalian"] ,
    status: "Vivo"
  },
  {
    id: 38,
    name: "Lia",
    team: null,
    image: "./assets/lia.png",
    Raça: "Elfo",
    gender: "Feminino",
    age: "?",
    ageType: "unknown",
    occupation: "NPC",
    affiliation: ["Lojista", "Bysaes Till"] ,
    status: "Vivo"
  },
  {
    id: 39,
    name: "Fenian Olawenys",
    team: null,
    image: "./assets/fenian_olawenys.png",
    Raça: "Elfo",
    gender: "Masculino",
    age: "?",
    ageType: "unknown",
    occupation: "NPC",
    affiliation: ["Bysaes Till"] ,
    status: "Vivo"
  },
  {
    id: 40,
    name: "Edyrm",
    team: null,
    image: "./assets/edyrm.png",
    Raça: "Elfo",
    gender: "Masculino",
    age: "?",
    ageType: "unknown",
    occupation: "NPC",
    affiliation: "Bysaes Till" ,
    status: "Vivo"
  },
  {
    id: 41,
    name: "Pedro",
    team: "Claret Orders",
    image: "./assets/pedro.png",
    Raça: "Tabaxi",
    gender: "Masculino",
    age: "?",
    ageType: "unknown",
    occupation: "NPC",
    affiliation: "Claret Orders" ,
    status: "Vivo"
  },
  {
    id: 42,
    name: "Kelfyr",
    team: null,
    image: "./assets/kelfyr_amara.png",
    Raça: "Elfo",
    gender: "Masculino",
    age: "?",
    ageType: "unknown",
    occupation: "NPC",
    affiliation: ["Bysaes Till", "Guarda"] ,
    status: "Vivo"
  },
  {
    id: 43,
    name: "Amara",
    team: null,
    image: "./assets/kelfyr_amara.png",
    Raça: "Elfo",
    gender: "Feminino",
    age: "?",
    ageType: "unknown",
    occupation: "NPC",
    affiliation: "Bysaes Till" ,
    status: "Vivo"
  },
  {
    id: 44,
    name: "Enrico Seraphim",
    team: null,
    image: null,
    Raça: "Humano",
    gender: "Masculino",
    age: "?",
    ageType: "unknown",
    occupation: "NPC",
    affiliation: "Desconhecido" ,
    status: "Vivo"
  },
  {
    id: 45,
    name: "Zilong",
    team: "Alma de Cobalto",
    image: "./assets/zilong.png",
    Raça: "Humano",
    gender: "Masculino",
    age: 24,
    ageType: "exact",
    occupation: "NPC",
    affiliation: ["Alma de Cobalto", "Penas de Morte"] ,
    status: "Vivo"
  },
  {
    id: 46,
    name: "Ziellos",
    image: null , 
    team: "Culto de Orcus",
    image: "./assets/ziellos.png",
    Raça: "Humano",
    gender: "Masculino",
    age: 38,
    ageType: "exact",
    occupation: "NPC",
    affiliation: ["Culto de Orcus", "Orcus"] ,
    status: "Morto-Vivo"
  },
  {
    id: 47,
    name: 'Ildan Greyroot',
    image: "./assets/ildan.png",
    team: null ,
    Raça: 'Humano',
    gender: 'Masculino' , 
    age: 22 ,
    agetype: 'exact' ,
    occupation: 'NPC' ,
    affiliation: ['Penas de Morte', 'O Sussurrado'] ,
    status: 'Vivo' , 
  },
  {
    id: 48,
    name: 'Erastus Greyroot',
    image: null,
    team: 'Os Remanescentes',
    Raça: 'Humano',
    gender: 'Masculino',
    age: 49,
    ageType: 'exact',
    occupation: 'NPC',
    affiliation: ['Os remanescentes', 'O Sussurrado'],
    status: 'Morto?',
  },
  {
    id: 49,
    name: 'Gshar Du',
    image: './assets/gashur.png',
    team: null,
    Raça: 'Duergar',
    gender: 'Masculino',
    age: 60,
    ageType: 'exact',
    occupation: 'NPC', 
    affiliation: 'O Cego',
    status: 'Morto',
  },
  {
    id: 50,
    name: 'Leucis',
    image:  './assets/leucis.png',
    team:  'Sorriso Áureo',
    Raça: 'Tiefling',
    gender: 'Masculino',
    age: 24,
    ageType: 'exact', 
    occupation: 'NPC', 
    affiliation: ['Sorriso Áureo', 'Penas de Morte'],
    status: 'Vivo' ,
  },
  {
    id: 51,
    name: 'Sarah',
    image: './assets/sarah.png', 
    team:  'Liga dos Milagres',
    Raça: 'Humano',
    gender: 'Feminino',
    age: 24,
    ageType: 'exact', 
    occupation: 'NPC',
    affiliation: 'Liga dos Milagres',
    status: 'Vivo',
  },
  {
    id: 52,
    name: 'Nasima Guillian',
    image:  './assets/Nasima.png',
    team:  'Ashari',
    Raça: 'Genasi',
    gender: 'Masculino',
    age: 17,
    ageType: 'exact', 
    occupation: 'Player',
    affiliation: ['Ashari', 'Penas de Morte', 'Alabastro'],
    status: 'Morto'
  },
  {
    id: 53,
    name: 'Eduardo Eldwyn',
    image:  null,
    team: 'Liceu de Alabastro', 
    Raça: 'Humano',
    gender: 'Masculino',
    age: 18,
    ageType: 'exact',
    occupation: 'Player',
    affiliation: 'Liceu de Alabastro',
    status: 'Vivo'
  },
  {
    id: 54,
    name: 'Alfredo Eldwyn',
    image:  null,
    team:  'Liceu de Alabastro',
    Raça: 'Warhammer',
    gender: 'Masculino',
    age: 17,
    ageType: 'exact' ,
    occupation: 'Player',
    affiliation: 'Liceu de Alabastra', 
    status: 'Vivo',
  },
  {
    id: 55,
    name: 'Alasterre de Vitrevos',
    image:  './assets/alasterreDeVitrevos.png',
    team: 'Claret Orders', 
    Raça: 'Humano',
    gender: 'Masculino',
    age: 30,
    ageType: 'exact', 
    occupation: 'NPC',
    affiliation: 'Claret Orders',
    status: 'Vivo',
  },
  {
    id: 56,
    name: 'Jorick LaMesh',
    image: './assets/JorickLamesh.png',
    team:  'Claret Orders',
    Raça: 'Humano',
    gender: 'Masculino',
    age: 33,
    ageType: 'exact',
    occupation: 'NPC',
    affiliation: 'Claret Orders',
    status: 'Vivo',
  },
  {
    id: 57,
    name: 'Teresa Dulamar',
    image: './assets/TeresaDulamar.png',
    team:  'Claret Orders',
    Raça: 'Anão',
    gender: 'Feminino',
    age: 80,
    ageType: 'exact', 
    occupation: 'NPC',
    affiliation: 'Claret Order',
    status: 'Vivo',
  },
  {
    id: 58,
    name: 'Vogal', 
    image:  './assets/Vogal.png',
    team:  'Claret Orders',
    Raça: 'Kenku',
    gender: 'Neutro',
    age: 16,
    ageType: 'exact', 
    occupation: 'NPC',
    affiliation: 'Claret Orders',
    status: 'Vivo',
  },
  {
    id: 59,
    name: 'Verruga',
    image: './assets/Verruga.png', 
    team: 'Demônios', 
    Raça: 'Demonio',
    gender: 'Masculino',
    age: 1500,
    ageType: 'atLeast',
    occupation: 'NPC',
    affiliation: ['Ildan','Orcus'],
    status: 'Vivo',
  },
  {
    id: 60,
    name: 'Erband Borrowspine',
    image: './assets/ErbandBorrowspine.png', 
    team:  'Família Borrowspine',
    Raça: 'Anão',
    gender: 'Masculino',
    age: 87,
    ageType: 'exact', 
    occupation: 'NPC',
    affiliation: 'Família Borrowspine',
    status: 'Morto',
  },
  {
    id: 61,
    name: 'Rei Thangrul ||',
    image: './assets/ReiThangrul.png',
    team:  null,
    Raça: 'Duergar',
    gender: 'Masculino',
    age: 79,
    ageType: 'exact', 
    occupation: 'NPC',
    affiliation: 'Torog',
    status: 'Morto',
  },
  {
    id: 62,
    name: 'Mythriel',
    image:  './assets/Mythriel.png',
    team: 'Desacorrentados', 
    Raça: 'Duergar',
    gender: 'Feminino',
    age: 32,
    ageType: 'exact', 
    occupation: 'NPC',
    affiliation: ['Dessacorrentados','Família Monárquica de Emberhold'],
    status: 'Vivo',
  },
  {
    id: 63,
    name: 'Hella Khaszal',
    image: './assets/HellaKhaszal.png',
    team: null,
    Raça: 'Humanno',
    gender: 'Feminino',
    age: 41,
    ageType: 'exact', 
    occupation: 'NPC',
    affiliation: ['Aizen','Dimitri','Belial','Fierna','Sythaeryn'],
    status: 'Vivo',
  },
  {
    id: 64, 
    name: 'Dimitri Khaszal',
    image: './assets/DimitriKhaszal.png', 
    team:  null,
    Raça: 'Meio-Elfo',
    gender: 'Masculino',
    age: 8,
    ageType: 'exact', 
    occupation: 'NPC',
    affiliation: ['Hella','Aizen','Synthaerin'],
    status: 'Vivo',
  },
  {
    id: 65,
    name: 'Sythaeryn Dricat',
    image: './assets/SythaerynDricat.png', 
    team: null,
    Raça: 'Meio-Elfo',
    gender: 'Masculino',
    age: 42,
    ageType: 'exact', 
    occupation: 'NPC',
    affiliation: ['Hella','Aizen','Dimitri'],
    status: 'Morto',
  },
  {
    id: 66,
    name: 'Aragorn',
    image:  './assets/Aragorn.png',
    team:  'Claret Orders',
    Raça: 'Humano',
    gender: 'Masculino',
    age: 25,
    ageType: 'exact',
    occupation: 'NPC',
    affiliation: ['Claret Orders','Penas de Mortes'],
    status: 'Morto',
  },
  {
    id: 67, 
    name: 'Rhaegar',
    image: './assets/Rhaegar.png',
    team:  'BoneBreakers',
    Raça: 'Kobold',
    gender: 'Masculino',
    age: 23,
    ageType: 'exact',
    occupation: 'Player',
    affiliation: ['BB','Harpistas','Corte Seelie','Chapéus de Palha'],
    status: 'Vivo',
  },
  {
    id: 68,
    name: 'Zariel Merigold',
    image:  './assets/ZarielMerigold.png',
    team: 'BloodHunters',
    Raça: 'Aasimar',
    gender: 'Masculino',
    age: 22,
    ageType: 'exact', 
    occupation: 'Player',
    affiliation: 'BloodHunters',
    status: 'Vivo'
  },
  {
    id: 69,
    name: 'Triss Merigold',
    image:  './assets/TrissMerigold.png',
    team:  'BloodHunters',
    Raça: 'Humano',
    gender: 'Feminino',
    age: 23,
    ageType: 'exact', 
    occupation: 'NPC',
    affiliation: 'BloodHunters',
    status: 'Vivo',
  }

];